name: Publish
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Cache 📦
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Node Environment ⬢
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install 🔧
        run: npm install

      - name: Latest
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Conditional
        id: cond
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ contains(steps.tag.outputs.tag, '-') }}
          if_true: "next"
          if_false: "latest"

      - name: Publish 📦
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          tag: ${{ steps.cond.outputs.value }}
          access: public
          check-version: true

      - name: Release
        if: steps.publish.outputs.type != 'none'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.publish.outputs.version }}
          generateReleaseNotes: true
          prerelease: ${{ contains(steps.publish.outputs.type, 'pre') }}
          token: ${{ secrets.GITHUB_TOKEN }}
